# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: detect-private-key
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        pass_filenames: false
        always_run: true
        args: ['--check', '.']
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        always_run: true
        args: ['--ignore=E203,W503', '--exclude=.venv/', --max-line-length=88]
